### ISSUE TITLE
你好请问本科毕业论文想用应该怎么修改？

### ISSUE THREAD

**Issue by robertlee2014** [TwistedW/HFUT-Graduate-Thesis#1]
你好请问本科毕业论文想用应该怎么修改？

**Comment by TwistedW** [comment]
> 你好请问本科毕业论文想用应该怎么修改？

按照你的本科毕设的需要，更改图标和一些默认参数就好，这段时间我会抽空进行最后版本的发布，前段时间整完一直忘记传了！

**Comment by robertlee2014** [comment]
好的，多谢
